---
layout: cv
title: Shelton Macamo's CV
---
# Shelton Macamo
Aspiring Sofware Engineer, College Junior, Cloud enthusiast.

<div id="webaddress">
<a href="mac21044@byui.edu">my email address</a>
| <a href="https://www.linkedin.com/in/shelton-macamo-604b001bb/?trk=opento_sprofile_details">My LinkedIn page</a>
</div>


## Currently

Persuing a bachelor's degree in computer science with a focus on cloud engineering

### Specialized in

Cloud Engineering. Specifically working with the AWS cloud platform.


### Personal interests

Soccer, Programming, Marvel Movies, Working out


## Education

`2006 - 2012`
__Forest Hill Primary Schol, Johannesburg South Africa.__

`2013 - 2017`
__Sir John Adamson High School,Johannesburg South Africa__

`2022 - Present`
__BYU-Idaho, Rexburg Idaho__


## Awards

`2012`
President, *Royal Society*, London, UK

Associate, *French Academy of Science*, Paris, France


## Skills

### Advanced:
- CSS
- HTML
- C#
- Python

### Competent
- Git/Github
- Communication
- Good collaborator


## Work Experience

`Association of Computer Machinery Society | BYU-Idaho`

- Vice President from April 2023 - October 2023
•   Participated as a judge during the Fall 2023 BYU-I hackathon
•   Actively planned and coordinated the operation of the entire hackathon with my team
•   Developed the FAQ page for the BYU-I hack website using React, and JavaScript

<div id="webaddress">
| <a href="https://byuihack.org/FAQ">Website I helped to build</a>
</div>


`BYU-Idaho IT department`

- *Assistant I-Learn Administrator from April 2022 - Present:*
- I Resolved issues that students and faculty have with the University’s online learning software. 
- I Resolved tickets in a timely manner, which helps both the students and faculty remain productive with the use of the online learning software. 

`Volunteering`
- Missionary for the LDS Church in Angola, Luanda between September 2018 – October 2020 


---
layout: cv
title: Shelton Macamo's CV
---
# Shelton Macamo
Aspiring Sofware Engineer, College Junior, Cloud enthusiast.

<div id="webaddress">
<a href="mac21044@byui.edu">my email address</a>
| <a href="https://www.linkedin.com/in/shelton-macamo-604b001bb/?trk=opento_sprofile_details">My LinkedIn page</a>
</div>


## Currently

Persuing a bachelor's degree in computer science with a focus on cloud engineering

### Specialized in

Cloud Engineering. Specifically working with the AWS cloud platform.


### Personal interests

Soccer, Programming, Marvel Movies, Working out


## Education

`2006 - 2012`
__Forest Hill Primary Schol, Johannesburg South Africa.__

`2013 - 2017`
__Sir John Adamson High School,Johannesburg South Africa__

`2022 - Present`
__BYU-Idaho, Rexburg Idaho__


## Awards

`2012`
President, *Royal Society*, London, UK

Associate, *French Academy of Science*, Paris, France


## Skills

### Advanced:
- CSS
- HTML
- C#
- Python

### Competent
- Git/Github
- Communication
- Good collaborator


## Work Experience

`Association of Computer Machinery Society | BYU-Idaho`

- Vice President from April 2023 - October 2023
•   Participated as a judge during the Fall 2023 BYU-I hackathon
•   Actively planned and coordinated the operation of the entire hackathon with my team
•   Developed the FAQ page for the BYU-I hack website using React, and JavaScript

<div id="webaddress">
| <a href="https://byuihack.org/FAQ">Website I helped to build</a>
</div>


`BYU-Idaho IT department`

- *Assistant I-Learn Administrator from April 2022 - Present:*
- I Resolved issues that students and faculty have with the University’s online learning software. 
- I Resolved tickets in a timely manner, which helps both the students and faculty remain productive with the use of the online learning software. 

`Volunteering`
- Missionary for the LDS Church in Angola, Luanda between September 2018 – October 2020 


